on:
  workflow_dispatch:
    inputs:
      package:
        type: string
        required: true
permissions: {}
jobs:
  pip-compile:
    name: ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
      with:
        python-version: '3.12.11' # 3.13 does not work at the moment
    - run: |
        python --version;
        python -m venv .venv;
        source .venv/bin/activate;
        pip install --require-hashes --requirement .github/workflows/pip-tools-requirements.txt;
        pip-compile --version;
        pip-compile --help;
        echo "${{ inputs.package }}" > ${{ runner.temp }}/requirements.in;
        pip-compile --annotate --strip-extras --generate-hashes --allow-unsafe --output-file ${{ runner.temp }}/requirements.txt ${{ runner.temp }}/requirements.in;
        deactivate;
        rm -r -f .venv;
        python -m venv .venv;
        pip install --require-hashes --requirement ${{ runner.temp }}/requirements.txt;
    - run: |
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: ${{ inputs.package }}-requirements.txt
        path: ${{ runner.temp }}/requirements.txt
        if-no-files-found: error
