on:
  workflow_dispatch:
    inputs:
      package:
        type: string
        required: true
permissions: {}
jobs:
  pip-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
      with:
        python-version: '3.12.11'
    - run: |
        python --version;
        python -m venv .venv;
        source .venv/bin/activate;
        pip install pip-tools;
        pip-compile --version;
        pip-compile --help;
        echo "${{ inputs.package }}" > ${{ runner.temp }}/requirements.in;
        pip-compile --annotate --strip-extras --generate-hashes --allow-unsafe---output-file ${{ runner.temp }}/requirements.txt ${{ runner.temp }}/requirements.in;
        deactivate;
        rm -r -f .venv;
        python -m venv .venv;
        pip install --require-hashes --requirement ${{ runner.temp }}/requirements.txt;
    - run: |
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ inputs.package }}-requirements.txt
        path: ${{ runner.temp }}/requirements.txt
        if-no-files-found: error
