on:
  workflow_dispatch:
    inputs:
      package:
        type: string
        required: true
permissions: {}
jobs:
  pip-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
      with:
        python-version: '3'
    - run: |
        pip install pip-tools
        echo "${{ inputs.package }}" > ${{ runner.temp }}/requirements.in
    - run: |
        pip-compile --annotate --strip-extras --rebuild --generate-hashes --output-file ${{ runner.temp }}/requirements.txt ${{ runner.temp }}/requirements.in
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ inputs.package }}-requirements.txt
        path: ${{ runner.temp }}/requirements.txt
        if-no-files-found: error
