on:
  pull_request_target:
    branches: ["main"]
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

permissions: {}

name: test

jobs:
  job1:
    environment: scott
    env:
      FOO: "${{ vars.FOO || 'not set by environment...' }}"
      YOU: "${{ secrets.YOU || 'not set by environment...' }}"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1"
        id: step1
        run: |
          if [[ "${{ env.FOO }}" == "not set by environment..." ]]; then echo "FAIL"; else echo "SUCCESS"; fi;
          echo "FOO is \"${{ env.FOO }}\" and YOU is \"${{ env.YOU }}\" (a secret if available).";
          echo "EVENT: ${{ toJSON(github.event) }}"
